php:
  build: .
  ports: 
    - "3000:80"
  volumes:
    - "./www:/var/www/html"
  links:
    - db
db:
  image: mysql
  volumes:
   - /var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=123
   - MYSQL_DATABASE=123
